name: Maven Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"
      developmentVersion:
        description: "Default version to use for new local working copy."
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout source code, set up Java, etc. Then...
      - uses: actions/checkout@v3
      - name: Configure Git User
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          server-id: srs-maven2
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Maven Release
        run: echo "mvn release:prepare release:perform -U -Dresume=false -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.developmentVersion }}"
        env:
          MAVEN_USERNAME: ${{ secrets.M2_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.M2_PASSWORD }}
